TestProj/ViewModels/MinMedianMaxViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestProj.ViewModels
{
    public class MinMedianMaxViewModel
    {
        public decimal? MinValue { get; set; }
        public decimal? MaxValue { get; set; }
        public decimal? MedianValue { get; set; }
    }
}

TestProj/Controllers/ExcelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using System.Net.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Text;
using TestProj.ViewModels;

namespace TestProj.Controllers
{
    [Produces("application/json")]
    [Route("ImportExcel")]
    public class ExcelController : Controller
    {
        private IHostingEnvironment _env;
        public ExcelController(IHostingEnvironment env)
        {
            _env = env;
        }
        [ActionName("Importexcel")]
        [HttpPost]
        public ActionResult Importexcel()
        {
            MinMedianMaxViewModel result = new MinMedianMaxViewModel();
            IFormFile file = Request.Form.Files[0];
            string webRootPath = _env.WebRootPath;
            string folderName = "Upload";
            string newPath = Path.Combine(webRootPath, folderName);
            string fullPath = Path.Combine(newPath, file.FileName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
                using (FileStream fs = System.IO.File.Create(fullPath))
                {
                    file.CopyTo(fs);
                    fs.Flush();
                }
            }
            else
            {
                if (!System.IO.File.Exists(fullPath))
                {
                    using (FileStream fs = System.IO.File.Create(fullPath))
                    {
                        file.CopyTo(fs);
                        fs.Flush();
                    }
                }
            }
            if (Request.Form.Files["FileUpload1"].Length > 0)
            {
                string extension  = Path.GetExtension(file.FileName).ToLower();
                string[] validFileTypes = { ".xls", ".xlsx", ".csv" }; //Avishek: for now only csv
               
             
                if (validFileTypes.Contains(extension))
                {
                    if (extension == ".csv")
                    {
                        List<decimal> ExcelValues = Utility.Utility.ConvertCSVtoList(fullPath);
                        result.MinValue=ExcelValues.Min();
                        result.MaxValue = ExcelValues.Max();
                        decimal[] ExcelValuesToArray = ExcelValues.ToArray();
                        result.MedianValue = Utility.Utility.GetMedian(ExcelValuesToArray);
                       
                    }

                }
                else
                {
                    ViewBag.Error = "Please Upload Files in .csv format";

                }
                System.IO.File.Delete(fullPath); //remove file from Directory

            }
            return View(result);

        }



    }
}

TestProj/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TestProj.Database.Tables;
using TestProj.Services.Base;

namespace TestProj.Controllers
{
    [Produces("application/json")]
    [Route("api/Person")]
    public class PersonController : Controller
    {
       // protected IPersonRepository _personRepository;
        private IRepositoryBase<Person> _repository = null;
        public PersonController(IRepositoryBase<Person> repository)
        {
            _repository = repository;
        }

        [HttpGet]
        [Route("/Person/GetList")]
        public IActionResult GetAllPerson()
        {
            var result=  _repository.GetAll();
            return Ok(result);
        }

        [HttpGet]
        [Route("/Person/GetByID")]
        public IActionResult GetByID(int PersonID)
        {
            var result = _repository.GetById(PersonID);
            return Ok(result);
        }

        [HttpPost]
        [Route("/Person/Create")]
        public IActionResult CreatePerson([FromBody] Person model)
        {
            model.CreatedTS = DateTime.Now;
            _repository.Insert(model);
            _repository.Save();
            return Ok();
        }

        [HttpPost]
        [Route("/Person/Update")]
        public IActionResult UpdatePerson([FromBody] Person model)
        {
            model.ModifiedTS = DateTime.Now;
           _repository.Update(model);
            _repository.Save();
            return Ok();
        }

        [Route("/Person/Delete")]
        public ActionResult Delete(int PersonID)
        {
            _repository.Delete(PersonID);
            _repository.Save();
            return Ok();
        }
        }
    }

TestProj/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestProj.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TestProj/Pages/Excel.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestProj.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

TestProj/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestProj.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TestProj/Pages/Excel.cshtml
@page

@using (Html.BeginForm("Importexcel", "Excel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr><td  style="padding:10px;">Excel file</td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
        <tr><td></td><td><input class="btn btn-primary" type="submit" id="Submit" name="Submit" value="Submit" /></td></tr>
    </table>
}

TestProj/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<style>
    .col-form-label {
        padding: 10px;
    }
</style>
<h3>Person List</h3>
<div ng-controller="PersonCtrl as vm">
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" ng-click="vm.OpenNew()">Create Person</button>
    <div class="row" style="padding:15px">
        <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0">
            <thead>
                <tr>
                    <th class="th-sm">
                        First Name
                    </th>
                    <th class="th-sm">
                        Last Name
                    </th>
                    <th class="th-sm">
                        Email
                    </th>
                    <th class="th-sm">
                        Address
                    </th>
                    <th class="th-sm">
                        Department
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="items in vm.PersonList">
                    <td>{{items.firstName}}</td>
                    <td>{{items.lastName}}</td>
                    <td>{{items.email}}</td>
                    <td>{{items.address}}</td>
                    <td>{{items.departmentName}}</td>
                    <td>
                        <button class="btn btn-primary" data-toggle="modal" data-target="#myModal"  ng-click="vm.OpenEditModal(items.personID)">Edit</button>
                        <button class="btn btn-danger" ng-click="vm.DeletePerson(items.personID)">Delete</button>
                    </td>
                </tr>
            </tbody>
        </table>

        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 ng-hide="vm.IsEdit" class="modal-title">Create User</h4>
                        <h4 ng-show="vm.IsEdit" class="modal-title">Edit User</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group row">
                            <label for="firstName" class="col-sm-2 col-form-label">First Name</label>
                            <div class="col-sm-10">
                                <input ng-model="vm.PersonDetails.firstName" type="text" class="form-control" id="firstName" placeholder="First Name">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lastName" class="col-sm-2 col-form-label">Last Name</label>
                            <div class="col-sm-10">
                                <input ng-model="vm.PersonDetails.lastName" type="text" class="form-control" id="lastName" placeholder="Last Name">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                <input ng-model="vm.PersonDetails.email" type="text" class="form-control" id="email" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="address" class="col-sm-2 col-form-label">Address</label>
                            <div class="col-sm-10">
                                <input ng-model="vm.PersonDetails.address" type="text" class="form-control" id="address" placeholder="Address">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="department" class="col-sm-2 col-form-label">Department</label>
                            <div class="col-sm-10">
                                <input ng-model="vm.PersonDetails.departmentName" type="text" class="form-control" id="department" placeholder="Department">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button ng-hide="vm.IsEdit" type="button" class="btn btn-success" data-dismiss="modal" ng-click="vm.CreatePerson(vm.PersonDetails)">Save</button>
                        <button ng-show="vm.IsEdit" type="button" class="btn btn-success" data-dismiss="modal" ng-click="vm.UpdatePerson(vm.PersonDetails)">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TestProj/Pages/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProj</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
     
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Index</a></li>
                    <li><a asp-page="/Excel">Export </a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TestProj</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/angular/angular.min.js"></script>
        <script src="~/js/angular/app.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/notify.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TestProj/Views/Excel/Importexcel.cshtml
@model TestProj.ViewModels.MinMedianMaxViewModel

@{
    ViewData["Title"] = "Importexcel";
    Layout = "~/Pages/_Layout.cshtml";
}
<style>
    .export {
        padding: 10px;
        background: #27ff0052;
        margin-bottom: 10px;
    }
</style>
<h2>Imported from excel</h2>
<span>@ViewBag.Error</span>

    <div class="export">
        <label>Max Value: </label>
        <span>@Model.MaxValue</span>
    </div>
    <div class="export">
        <label>Median Value: </label>
        <span>@Model.MedianValue</span>
    </div>
    <div class="export">
        <label>Min Value: </label>
        <span>@Model.MinValue</span>
    </div>